### PR TITLE
Updated marketplace header and filter panel

### PR DESCRIPTION
**Pull request by electrovir**
- updated header:
    new-header
- filter panel opened:
    filter-panel-open
- sort dropdown opened:
    sort-dropdown
- filter panel on skinny screens:
    skinny-filters

### CODE REVIEW

**Comment by bodily11** [comment]
Sliders have huge ranges. Any chance we can do a log based slider? Like ticks would be:
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300, 400, etc. This would make it much easier to use I think.

**Comment by ponnexcodev** [comment]
@bodily11 Having ticks on the slider would make it even harder for the user UX-wise especially if the range is huge as the slider's length is fixed while the resolution gets bigger. We can scale the ticks based on how huge the range is but still would be hard for the user to select the right amount. My suggestion would be to have the slider label/s editable. This would come in handy especially on double-range if the ranges are close to each other. This would give the user freedom to either use the slider or input the amount right away.

**Comment by bodily11** [comment]
Yes, we could allow for editable values in the range, that is one interesting idea.

I don't think I agree that having log based snap points for the slider is a bad idea though. As you get bigger values, you don't need as fine grained control over the filtering.

Like we could just use these snap points for all volume or price based filters:
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10k, 20k, 30k, 40k, 50k, 60k, 70k, 80k, 90k, 100k, 200k, 300k. 

Then it is fairly easy to pick your range, with more fine grained control on the smaller end, and less control needed on the higher end.

Does this make sense?

**Comment by mgogles** [comment]
In the designs for the Volume slider, we also have 7-day, 30-day, All-time filters. Can we include that here? Screenshot: 
image

**Comment by mgogles** [comment]
When some items are active (slider, dropdown) we're adding a green border around the entire element. With the dropdown, it looks funny because the border is being cut off. With the slider, it looks funny because it's so tight around the UI element. I think we can remove this border altogether.
image
image

**Comment by mgogles** [comment]
The page search box is a bit small, I think we should extend it quite a bit (at least in web version), probably at least the width of the "All Collections" header.
image

**Comment by electrovir** [comment]
> log based slider

@bodily11, we can add this.

> 7-day, 30-day, All-time filters

@mgogles I tried to find data to use for these but found nothing. If you or @stephenandrews know where that data is, then I can setup those toggles.

> green border around the entire element

@mgogles the borders are for accessibility purposes: you can see what element is selected when you tab around on the page. Good catch on them looking weird. Would you prefer we fix them or remove them entirely? (I would recommend fixing them as accessibility is very important imo but it's your call.)

> search box is a bit small, I think we should extend it quite a bit

@mgogles will do!

**Comment by mgogles** [comment]
@electrovir let's leave the accessible elements but just clean them up a bit. So make sure the whole border is displayed on the dropdown, and perhaps try for more space around the slider if that's possible. (add padding so the border isn't quite so tight around the slider)

**Comment by electrovir** [comment]
Log-like slider has been implemented!

**Comment by electrovir** [comment]
* toniq slider focus border has been fixed:
    slider-focus
* search input has been widened:
    search

**Comment by electrovir** [comment]
@mgogles I can no longer repro the dropdown focus getting cut off. Do you still see that? It might've been accidentally fixed by something else already haha

**Comment by electrovir** [comment]
Merged now so that this doesn't get stale. We will add the volume filters once the data is available.

**Pull request merged**
