### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by electrovir**
Update dependencies:
- exclude `react-material-ui-carousel` as an update breaks its use here and it doesn't trigger npm's security audit so it's fine to leave.
- Updates cut build times by an order of magnitude: 5 minutes -> 12 seconds (rough numbers)
- Updates cut npm audit reports down to almost nothing.
- `react-router-dom` update changes the API. `useNavigate` is now used instead of `useHistory` and just plain `navigate()` instead of `history.push()`.
- `react-app-rewired` is used now instead of `react-scripts` so we can override the webpack config with `config-overrides.js` 
    - account for webpack no longer automatically polyfilling Node.js modules
    - generate same chunking as in webpack 4
- change `prebuild` npm script to `serve` because it was causing `npm run build` to run the full build twice
- update `browserslist` via `npx browserslist@latest --update-db`
- add `serve` dev dependency because it was missing.

### CODE REVIEW

**Comment by stephenandrews** [comment]
Hi there - can't seem to get it to run locally with npm run start - any pointers to the fix?

**Comment by electrovir** [comment]
> Hi there - can't seem to get it to run locally with npm run start - any pointers to the fix?

@stephenandrews did you run `npm install` first?

**Comment by stephenandrews** [comment]
Yeah, I deleted node_modules and ran `npm i` but no go. I can complete `npm run build` and then serve it and it's fine, but `npm run start` just hangs on the "Starting the development server"

**Comment by stephenandrews** [comment]
I can build and serve, which is fine for now, but I need to figure out why I can't run `npm run start`...

**Pull request merged**
