### PR TITLE
Single nft refresh page

### PR DESCRIPTION
**Pull request by ponnexcodev**
- Desktop:
screencapture-localhost-3000-marketplace-asset-la26x-mykor-uwiaa-aaaaa-b4aen-eaqca-aaeoz-q-2022-08-12-14_51_33

- Mobile:
screencapture-localhost-3000-marketplace-asset-la26x-mykor-uwiaa-aaaaa-b4aen-eaqca-aaeoz-q-2022-08-12-14_51_54

- Set Attributes data to "No Attributes" for now as there's no data yet
screencapture-localhost-3000-marketplace-asset-la26x-mykor-uwiaa-aaaaa-b4aen-eaqca-aaeoz-q-2022-08-12-14_52_21

### CODE REVIEW

**Comment by mgogles** [comment]
Nice work Francis, this is looking awesome! I noticed that in the preview the content box isn't as wide as the design -- can we make the box wider in the web view to match the design more closely? (the mobile version in fine). Example:

**Box Width in Current Preview**
image

**Box Width in Design**
image

**Comment by mgogles** [comment]
Also, I noticed that the background color is #F9F9F9 (instead of #FFF like in the designs) but I am assuming that's because this PR is focusing on the page UI, not the universal bg color.

**Comment by ponnexcodev** [comment]
Yes, I'm just focusing on the page UI and it just occurred to me last week we're merging to `refresh-ui` instead of `main` so I did not do the background since it's site-wide. But since we're merging to `refresh-ui` branch I might do the background.

**Comment by ponnexcodev** [comment]
@mgogles added fixes for the background and the page UI width

**Comment by mgogles** [comment]
@ponnex  The the main image at the top and the smaller avatar image in the rows are displaying these scroll bars.

image

**Comment by ponnexcodev** [comment]
@mgogles I can't replicate the issue on the latest build [above](https://deploy-preview-149--friendly-raman-30db7b.netlify.app/). What browser and screen size did you use?

**Comment by ponnexcodev** [comment]
@mgogles was able to replicate now on Motoko Mechs collection with images that use iframe. I'll create a PR for the fix :)

**Comment by bodily11** [comment]
To be clear, this isn't a new design system error. This is a Motoko Mech error. We need to adjust the way Motokos are rendered within the Iframe itself to fix the detail view. 

The thumbnail feels like it needs to be updated though. We shouldn't have scroll bars in the thumbnail view.

**Comment by ponnexcodev** [comment]
@bodily11 Motoko Mech has a fixed 500x700 content, iframe fixes via styles/CSS are limited and doesn't do much unless we go deeper into the iframe content, which we'll also face a cross-origin frame problem. Is there a way we can create a PR or changes in Motoko Mech to make content responsive?

**Comment by bodily11** [comment]
Yes, don't worry about Motoko Mech display. We'll fix separately, you don't have to do this. (plan is to modify the NFT so that it is responsive by itself. :)

**Comment by ponnexcodev** [comment]
@mgogles @bodily11 created a PR for the fix please see https://github.com/Toniq-Labs/entrepot-app/pull/162

**Pull request merged**
